### ISSUE TITLE
AsyncDownloaderProxy: Couldn't find proxy method 'getEnableCertificateValidation' with signature '()Z'

### ISSUE THREAD

**Issue by cmelian** [mano-mykingdom/downloader#4]
Hi,

I use Titanium 3.5.0.GA and testing in Genymotion VM with Android 5.1.0
There is an error wich crashes app:

```
[ERROR] :  AsyncDownloaderProxy: Couldn't find proxy method 'getEnableCertificateValidation' with signature '()Z'
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:135)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[WARN] :   W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/mykingdom/downloader/AsyncDownloaderProxy;.getEnableCertificateValidation()Z"
```

Same error and crash with ANdroid 4.4.4

```
[ERROR] :  AsyncDownloaderProxy: Couldn't find proxy method 'getEnableCertificateValidation' with signature '()Z'
[WARN] :   dalvikvm: Invalid indirect reference 0xa505bd18 in decodeIndirectRef
[INFO] :   dalvikvm: "KrollRuntimeThread" prio=5 tid=11 RUNNABLE
[INFO] :   dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0xa4fcea88 self=0xb87f2340
[INFO] :   dalvikvm:   | sysTid=1964 nice=0 sched=0/0 cgrp=apps handle=-1200056328
[INFO] :   dalvikvm:   | state=R schedstat=( 3537487237 20744003 463 ) utm=26 stm=327 core=1
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[INFO] :   dalvikvm:   at android.os.Handler.dispatchMessage(Handler.java:98)
[INFO] :   dalvikvm:   at android.os.Looper.loop(Looper.java:136)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   dalvikvm:
```

**Comment by manojdcoder** [comment]
Is it same on real device? I have been using it and never found such issue on real device.
